### ISSUE TITLE
Publish library to maven central

### ISSUE THREAD

**Issue by ianhanniballake** [joaomgcd/TaskerPluginSample#1]
It appears like the `com.joaomgcd:taskerpluginlibrary` library is only published to JCenter.

JFrog [announced that they're shutting down](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), disallowing new updates on  and will stop serving artifacts entirely in early 2022.

In Android Studio Arctic Fox, there's even a Lint warning if you include `jcenter()` as a repository:

> JFrog announced that the JCenter Maven repository would reach end of service and would no longer be available from 1st May 2021; no new submissions would be accepted from 28th February 2021, and there might be accessibility problems due to maintenance windows before the end of service date.  We recommend configuring Gradle to retrieve Java artifacts using mavenCentral instead.
>
> Issue id: JcenterRepositoryObsolete 
> More info: https://developer.android.com/r/tools/jcenter-end-of-service

This lint warning currently needs to be suppressed to use the `taskerpluginlibrary`.

Can you publish the library to maven central? There's a number of [good guides](https://getstream.io/blog/publishing-libraries-to-mavencentral-2021) for setting that up.

**Comment by kanetik** [comment]
Another good resource: https://proandroiddev.com/publishing-existing-libraries-to-maven-central-1d08ae5d8f1

**Comment by joaomgcd** [comment]
Thanks. I'm working on this now.

**Comment by joaomgcd** [comment]
Ok, done! 😁 Hope this helps!

**Comment by kanetik** [comment]
Awesome, thanks!

**Comment by ianhanniballake** [comment]
Hmm, I'm running into issue in my project [muzei](https://github.com/muzei/muzei) when I [remove my jcenter repository](https://github.com/muzei/muzei/blob/main/main/build.gradle#L98):

```
> Could not resolve all files for configuration ':main:debugCompileClasspath'.
   > Could not find :unspecified:.
     Required by:
         project :main > com.joaomgcd:taskerpluginlibrary:0.4.0
```

Looking at the [POM file on maven central](https://search.maven.org/artifact/com.joaomgcd/taskerpluginlibrary/0.4.0/aar), I see this suspicious block:

```
<dependency>
    <groupId/>
    <artifactId>unspecified</artifactId>
    <version/>
</dependency>
```

So it appears something is wrong with the published artifact that wasn't present in the jcenter version.

Even worse, since I had `mavenCentral` higher up in the list of repositories compared to `jcenter`, my build is broken since it is preferring the broken `mavenCentral` version of the artifact.

Can you re-open this and publish a `0.4.1` fixed version?
