### ISSUE TITLE
Binary (aar) for release 0.4.3 on Maven Central is identical to 0.4.2

### ISSUE THREAD

**Issue by ribbons** [joaomgcd/TaskerPluginSample#16]
As a follow on from #15 (as sadly GitHub doesn't give me the option of re-opening the issue), unfortunately I think something has gone wrong as part of the release process to Maven Central as the compiled aar file is byte-for-byte the same as the one for the 0.4.2 release...  (The source code jar files are different however)

```
taskerpluginlibrary-0.4.2.aar.sha256: 92f492b9525be61f83b23449ea3c43425de0a2f5d2b44818df38cd16dd0bf65c
taskerpluginlibrary-0.4.3.aar.sha256: 92f492b9525be61f83b23449ea3c43425de0a2f5d2b44818df38cd16dd0bf65c
```

**Comment by ribbons** [comment]
@joaomgcd - would it be possible for you to take a look at this?

**Comment by ribbons** [comment]
@joaomgcd - would it be possible for you to take a look at this? (or is the library no-longer supported?)

**Comment by joaomgcd** [comment]
Hi. Very sorry for the delay.

I was finally able to take a look today and indeed, for some reason Android Studio was not building the latest version of the aar in the release variant.

I was able to figure out how to force it to do so now so I've now uploaded v 0.4.4 with the changes.

Sorry for the hold up!

**Comment by ribbons** [comment]
Awesome, thank you @joaomgcd :+1:
