### ISSUE TITLE
0.4.4 crashes with AGP 8 and R8 4.0.x

### ISSUE THREAD

**Issue by Tolriq** [joaomgcd/TaskerPluginSample#17]
Trying to figure out what changed but so far not able to.

Updating from 0.4.3 to 0.4.4 breaks things with Tasker complaining there's no more empty constructors. Even if I tweak R8 to keep more things, the plugin configuration is lost when going from tasker to app. (Add a task Tasker shows the data, edit the task the app does not receive the data, run the task the app does not receive the data).

**Comment by joaomgcd** [comment]
Hi! Sorry for the trouble! When does it complain about the empty constructors exactly? Is that at build-time? I'm trying to reproduce it but it's still working for me...

**Comment by Tolriq** [comment]
At runtime you can test Yatse in current prod 11.12.0 and see :( Since Google still have not validated the revert :(

**Comment by joaomgcd** [comment]
Sorry to hear that :(

Do you have a stack trace example of the crashes?

**Comment by Tolriq** [comment]
`hc.c`is a `@TaskerInputRoot` tested different variations, different R8 rules to keep the empty constructor best I could achieve would be no more crash but data not passed between tasker and the app.

```
Caused by: androidx.fragment.app.Fragment$InstantiationException: Tasker Input class hc.c must have empty constructor
 at com.joaomgcd.taskerpluginlibrary.input.TaskerPluginInputKt.getInputFromTaskerIntent$getNewInstance(TaskerPluginInput.kt:141)
 at com.joaomgcd.taskerpluginlibrary.input.TaskerPluginInputKt.getInputFromTaskerIntent$getInput(TaskerPluginInput.kt:148)
 at com.joaomgcd.taskerpluginlibrary.input.TaskerPluginInputKt.getInputFromTaskerIntent(TaskerPluginInput.kt:158)
 at com.joaomgcd.taskerpluginlibrary.extensions.InternalKt.getTaskerInput(Internal.kt:39)
 at com.joaomgcd.taskerpluginlibrary.config.TaskerPluginConfigHelper.onCreate(TaskerPluginConfigHelper.kt:71)
 at org.leetzone.android.yatsewidget.tasker.ActivityConfigTasker.onCreate(TaskerHelper.kt:35)
 at android.app.Activity.performCreate(Activity.java:8290)
 at android.app.Activity.performCreate(Activity.java:8269)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
```

Reverting to 0.4.3 instantly fix all cases.

**Comment by joaomgcd** [comment]
And you also used `@JvmOverloads constructor` on that input class?

**Comment by Tolriq** [comment]
I did not as not needed, but adding it did not change anything.  Also tested manual constructor adding.

As said in the title I'm using AGP 8.0 alpha 7 and R8 4.0.37 so maybe there's some new rules needed, but even adding a keep rule was not enough.

Only change would be kotlin 1.5.21 vs 1.5.0 and compilesdk 31 but I don't see the side effect.

**Comment by joaomgcd** [comment]
Ok, so, to clarify, this happens to you on your device if you simply try to run the Tasker action? Does it also happen in a debug build with no minifying going on?

**Comment by Tolriq** [comment]
It happens on every devices and no it only happens with R8 enabled. Running an existing action or just trying to add / edit one.

With new R8 keeps rules to force keep the empty constructor, all I can reach is no more crash, so can add an action. But when action is ran or edited the data is not passed back to the app.

So there's something changed in 0.4.4 about instance creation.

**Comment by joaomgcd** [comment]
Could you maybe share how you're configuring R8 on your build so I can try to reproduce it with my sample app? Thanks in advance!

**Comment by Tolriq** [comment]
In gradle.properties
`android.enableR8.fullMode=true`

In top buildScript
```
 maven { setUrl("https://storage.googleapis.com/r8-releases/raw") }
    dependencies {
        classpath("com.android.tools:r8:4.0.37")
        ... AGP and the rest
```

**Comment by joaomgcd** [comment]
I tried adding the same thing on [this](https://github.com/joaomgcd/TaskerPluginSample/tree/master/app) app but could not get it to crash.

Could you please try importing this app and try to change it to make the build process as much as yours as possible and see if you can get it to crash like Yatse?

**Comment by Tolriq** [comment]
I'll try to find time tomorrow.

**Comment by joaomgcd** [comment]
Thank you very much.

**Comment by Tolriq** [comment]
@joaomgcd you did not push 0.4.4 changes so it's hard to figure out. But I suppose you have updated Android Gradle plugin too?

The issue is that the proguard rules from the library are no more embedded in the published version. I think Google changed the way at some point and you need to specify (consumerProguardFiles in the gradle files)

**Comment by joaomgcd** [comment]
Hhmm, I did actually not change the Android gradle plugin recently. The files on Github are actually the latest ones save for the version number which I forgot to update before committing to Github. The rest is exactly the same.

What did change was actually the publishing method, which is now using a different plugin (because bintray stopped working) and maybe that can explain the differences. 

Because of an oversight on my part, versions 0.4.0, 0.4.1, 0.4.2 and 0.4.3 (all versions on maven central prior to the last one) all actually had the same aar file as the last bintray version, meaning that ever since I adopted the new publishing method I was mistakenly publishing the same aar over and over again.

A user recently spotted the error and I corrected it by publishing the actual latest code now.

How did you verify that the new artifacts did not include the proguard files?

If you include [these rules](https://github.com/joaomgcd/TaskerPluginSample/blob/master/taskerpluginlibrary/proguard-rules.pro) in your build does it work for you?

It's weird cause I tried using the latest library (0.4.4) on a build with minify enabled and it still worked correctly...

But if adding those rules can work for you I can change it to consumerProguardFiles and see if that helps.

**Comment by Tolriq** [comment]
You can edit the aar :)

I tested by removing the manual rules from the sample app and switching between 0.4.3. and 0.4.4.

Rules should be in the aar and not needed to be manually added on each consumer app. This is error prone and we do not get updated ones when updating the library.

**Comment by joaomgcd** [comment]
Thank you :) Yeah, I do want to make those rules part of the library, no question about it. I was just wondering if adding those rules to your app momentarily if it would fix the issues with v0.4.4 of the library. Does it fix it?

**Comment by Tolriq** [comment]
It does in the sample app with the same configuration so yes it will probably, my computer starts to be very old and release compile of Yatse is like 15 minutes :p

**Comment by joaomgcd** [comment]
Ok, thanks! I'll try using consumerProguardFiles and see if that fixes it. Thank you!

**Comment by joaomgcd** [comment]
Ok, I've updated both the github source and the release aar with the consumerProguardFiles parameter. Hopefully that fixes it! 

Can you please try it if you have the chance? Thanks!

**Comment by Tolriq** [comment]
I'll try tomorrow thanks.

**Comment by Tolriq** [comment]
It's fixed thanks.

**Comment by joaomgcd** [comment]
Awesome! :) Glad that did it! Thanks for testing!
