### ISSUE TITLE
TaskerPluginResultError's type is too restrictive

### ISSUE THREAD

**Issue by Waboodoo** [joaomgcd/TaskerPluginSample#18]
I might be misunderstanding how to use this, but to me it seems that `TaskerPluginResultError` can only be used if the output type is set to `Unit`, i.e., if no output is used.

In my case, I was so far using `TaskerPluginRunnerActionNoOutput`, where everything is working fine, but now I'd like to extend my app to allow returning data, so I'm changing this to `TaskerPluginRunnerAction<MyInput, MyOutput>`. This however leads me to the problem that the type-system no longer allows me to use `TaskerPluginResultError`, making it impossible for me to return errors. I considered just writing my own custom `TaskerPluginResultError` class but then had to realize that that is not possible either because `TaskerPluginResult` is a sealed class.

If this is not a bug but just my misunderstanding, please point me at an example of how to return errors when the output type is not `Unit`. I couldn't find one.

For reference, here's a summary of my class:

```kotlin
class TriggerShortcutActionRunner : TaskerPluginRunnerAction<Input, Output>() {

    override fun run(context: Context, input: TaskerInput<Input>): TaskerPluginResult<Output> {
        try {
            val result = doStuff();
            TaskerPluginResultSucess(Output(result))
        } catch (e: Exception) {
            // Here I can't use TaskerPluginResultError, because Unit is not a subtype of Output
            TaskerPluginResultError(0, "Error message goes here")
        }
    }
}
```

**Comment by joaomgcd** [comment]
Ok, added the [TaskerPluginResultErrorWithOutput](https://github.com/joaomgcd/TaskerPluginSample/blob/1b326960a8c271cde9e2da36053968735d68489b/taskerpluginlibrary/src/main/java/com/joaomgcd/taskerpluginlibrary/runner/TaskerPluginResult.kt#L24) class that allows you to do this.

Use
`implementation 'com.joaomgcd:taskerpluginlibrary:0.4.7'`
to use.

Hope this helps! :)

**Comment by Waboodoo** [comment]
Wow, that was quick, thanks for the fix. I have tested it and can confirm it solves my problem.

**Comment by joaomgcd** [comment]
Great :) Glad I could help!
