### ISSUE TITLE
mavenCentral version of 0.4.0 has dependency on 'undefined'

### ISSUE THREAD

**Issue by ianhanniballake** [joaomgcd/TaskerPluginSample#2]
I'm running into issue in my project [muzei](https://github.com/muzei/muzei) when I [remove my jcenter repository](https://github.com/muzei/muzei/blob/main/main/build.gradle#L98):

```
> Could not resolve all files for configuration ':main:debugCompileClasspath'.
   > Could not find :unspecified:.
     Required by:
         project :main > com.joaomgcd:taskerpluginlibrary:0.4.0
```

Looking at the [POM file on maven central](https://search.maven.org/artifact/com.joaomgcd/taskerpluginlibrary/0.4.0/aar), I see this suspicious block:

```
<dependency>
    <groupId/>
    <artifactId>unspecified</artifactId>
    <version/>
</dependency>
```

So it appears something is wrong with the published artifact that wasn't present in the jcenter version.

Even worse, since I had `mavenCentral` higher up in the list of repositories compared to `jcenter`, my build is broken since it is preferring the broken `mavenCentral` version of the artifact.

Can you re-open this and publish a `0.4.1` fixed version?

_Originally posted by @ianhanniballake in https://github.com/joaomgcd/TaskerPluginSample/issues/1#issuecomment-797832486_

**Comment by ianhanniballake** [comment]
I've been able to work around this issue by using

```
implementation ("com.joaomgcd:taskerpluginlibrary:$taskerVersion") {
    // Exclude required due to https://github.com/joaomgcd/TaskerPluginSample/issues/2
    exclude module: 'unspecified'
}
```

**Comment by Tolriq** [comment]
Would not have expected that Ian saved me on that one :)

```exclude(module = "unspecified")``` for kts

**Comment by joaomgcd** [comment]
Thanks very much. Forgive my noobness 😅
Fixed in 0.4.1. Can you confirm?

**Comment by Tolriq** [comment]
Fixed for my side thanks :)

**Comment by joaomgcd** [comment]
Cool! Thanks for confirming!

**Comment by ianhanniballake** [comment]
`0.4.1` works perfectly. Thanks for the quick fix 👍
