### ISSUE TITLE
Enable getting the task timeout duration

### ISSUE THREAD

**Issue by ribbons** [joaomgcd/TaskerPluginSample#21]
I'm interested in getting the timeout assigned by the user for the current plugin task (to allow cancelling a long running/hung task and return the progress so far back to Tasker before the timeout occurs).

I found [getHintTimeoutMS](https://github.com/joaomgcd/TaskerPluginSample/blob/1b326960a8c271cde9e2da36053968735d68489b/taskerpluginlibrary/src/main/java/net/dinglisch/android/tasker/TaskerPlugin.java#L677) but this requires a bundle to be passed in which (if my understanding is correct) isn't accessible from the app using this library, just internally.

Would it be possible to expose the timeout information so that it can be accessed in classes inheriting from `TaskerPluginRunnerAction`?  Alternatively, if it is actually possible to access this already an example would be much appreciated.

**Comment by joaomgcd** [comment]
Ok, it's actually pretty simple. I forgot to include it, sorry!

Are you able to build from source? If so, I have updated [this file](https://github.com/joaomgcd/TaskerPluginSample/blob/master/taskerpluginlibrary/src/main/java/com/joaomgcd/taskerpluginlibrary/action/TaskerPluginRunnerAction.kt). From your runner you now have the **requestedTimeout** property you can access.

Hope this helps!

**Comment by ribbons** [comment]
No need to apologise and that works perfectly - many thanks João!

**Comment by joaomgcd** [comment]
Awesome :) Glad it works!
