### ISSUE TITLE
Missing ActivityMainBinding Class Declaration

### ISSUE THREAD

**Issue by nbetcher** [joaomgcd/TaskerPluginSample#26]
Hello,
The class definition for `ActivityMainBinding` is missing from `com.joaomgcd.taskerpluginsample.databinding` in the Github repository. The class was introduced in [this](https://github.com/joaomgcd/TaskerPluginSample/commit/94b4643dba9b5d2aec62656fcedd1cd45fd8fecf) commit, but the corresponding sub-directory (`databinding`) is missing -- likely just needs a `git add`?

I didn't do a comprehensive evaluation of the remainder of the code to determine if there are any other missing source files.

**Comment by joaomgcd** [comment]
ActivityMainBinding is automatically generated by the compiler. As far as I know, it doesn't need to be included in the git, right? :)
