### ISSUE TITLE
TaskerInput and bindings

### ISSUE THREAD

**Issue by jmriego** [joaomgcd/TaskerPluginSample#4]
It seems like Android is moving now to ViewBindings instead of the previous way of interacting with views.
I have modified the example code so that it works with bindings:

```
class ActivityConfigTaskwarriorRun : ActivityConfigTasker<GetCommandInput, GetCommandOutput, GetCommandRunner, GetCommandHelper, ActivityConfigTaskwarriorRunBinding>() {
    //Overrides
    override fun getViewBinding() = ActivityConfigTaskwarriorRunBinding.inflate(layoutInflater)
    override fun getNewHelper(config: TaskerPluginConfig<GetCommandInput>) = GetCommandHelper(config)

    override fun assignFromInput(input: TaskerInput<GetCommandInput>) = input.regular.run {
        binding.editTextCommand.setText(command)
    }

    override val layoutResId = R.layout.activity_config_taskwarrior_run
    override val inputForTasker get() = TaskerInput(GetCommandInput(binding.editTextCommand.text?.toString()))
//    override val inputForTasker get() = TaskerInput(GetCommandInput("next"))

}
```

Bindings are initialized correctly and I can see the data but it seems like when the library calls inputForTasker, those bindings are not available any more. Any idea of what might be causing this? Thanks in advance!

**Comment by jmriego** [comment]
sorry, my fault, I missed one further change needed for getting the binding to work

**Comment by joaomgcd** [comment]
Thanks for the update! What else did you have to change, I'm curious? :)

**Comment by jmriego** [comment]
no worries! It seems like the only thing left was to bind the view properly. I was using a different method of doing this as it seems like there was a change in how to do this now.
```
abstract class ActivityConfigTasker<TInput : Any, TOutput : Any, TActionRunner : TaskerPluginRunner<TInput, TOutput>, THelper : TaskerPluginConfigHelper<TInput, TOutput, TActionRunner>, B : ViewBinding> : Activity(), TaskerPluginConfig<TInput> {
    abstract fun getNewHelper(config: TaskerPluginConfig<TInput>): THelper
    abstract val layoutResId: Int

    protected val taskerHelper by lazy { getNewHelper(this) }
    lateinit var binding: B

    open val isConfigurable = true
    override val context get() = applicationContext
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        var logger = Logger.forInstance(this)
        logger.d("binding initialized")
        binding = getViewBinding()
        val view = binding.root
        setContentView(view)

        if (!isConfigurable) {
            taskerHelper.finishForTasker()
            return
        }
        taskerHelper.onCreate()
    }

    override fun onKeyDown(keyCode: Int, event: KeyEvent): Boolean {
        return if (keyCode == KeyEvent.KEYCODE_BACK && event.repeatCount == 0) {
            val result = taskerHelper.onBackPressed()
            if (result is SimpleResultError) {
                alert("Warning", "Settings are not valid:\n\n${result.message}")
            }
            return result.success
        } else super.onKeyDown(keyCode, event)
    }

    override fun onBackPressed() {
    }

    abstract fun getViewBinding(): B
}
```

Here's the whole file: https://github.com/jmriego/TaskwarriorC2/blob/tasker_output/android/app/src/main/java/com/taskwc2/controller/tasker/ActivityConfigTasker.kt

I'm trying to add a Tasker plugin to the TaskWarrior Android app.
By the way, not sure if it's because there's just not a method at the moment, but how do you trigger the [BasicEvent](https://github.com/joaomgcd/TaskerPluginSample/blob/master/app/src/main/java/com/joaomgcd/taskerpluginsample/tasker/basic/BasicEvent.kt)? I can't get Tasker to detect this event but maybe this example is not really part of the app?

**Comment by joaomgcd** [comment]
There's a plugin event for this app called **Basic Event** which will trigger when you call `context.triggerBasicTaskerEvent()`. Is that not working for you?

**Comment by jmriego** [comment]
sorry, I just meant that I was trying to use the sample app included in this repo but I see that there's nothing calling `context.triggerBasicTaskerEvent()` right now. I was expecting maybe clicking on play/pause of the song should call this code. Thanks for all your help!

**Comment by joaomgcd** [comment]
Aahh you're right :) Ok, added that to the main screen of the app as an example! Thanks for the feedback!
