### ISSUE TITLE
[question] Computing output in the background with TaskerPluginRunnerAction 

### ISSUE THREAD

**Issue by Admicos** [joaomgcd/TaskerPluginSample#5]
Apologies if this isn't the right place for this. I am new to both Android dev and using this library, so this might just be something obvious for someone who knows what they're doing.

Anyways, I have this action runner class

```kotlin
class SActionRunner : TaskerPluginRunnerAction<SInput, SOutput>() {
    override fun run(
        context: Context,
        input: TaskerInput<SInput>
    ): TaskerPluginResult<SOutput> {
        val output = SOutput("lorem ipsum") // do important work
        return TaskerPluginResultSucess(output)
    }
}
```

When the action runs, I am planning on popping up a new activity, computing the `output` variable there, and returning it back to Tasker. The problem is, well, I have no idea how to do that.

I can't just compute the output variable here because a lot of the libraries I need to use do callbacks and stuff, which means even if I didn't pop up any activity, I'd still need a way to return the output from somewhere other than this method.

I could make it so this action returns immediately and triggers an event, but that doesn't sound too good from a usability point of view. Is there any way I can make this work?

Thanks in advance :)

**Comment by joaomgcd** [comment]
Ok, added an example of how to do that, complete with an activity and everything 😊

Check it out [here](https://github.com/joaomgcd/TaskerPluginSample/blob/master/app/src/main/java/com/joaomgcd/taskerpluginsample/tasker/backgroundwork/BackgroundWork.kt).

Hope this helps!
